//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExplanationSubagentDecisionAction.
const (
	Ask    ExplanationSubagentDecisionAction = "ask"
	Inject ExplanationSubagentDecisionAction = "inject"
	None   ExplanationSubagentDecisionAction = "none"
	Shadow ExplanationSubagentDecisionAction = "shadow"
	Skip   ExplanationSubagentDecisionAction = "skip"
)

// Valid indicates whether the value is a known member of the ExplanationSubagentDecisionAction enum.
func (e ExplanationSubagentDecisionAction) Valid() bool {
	switch e {
	case Ask:
		return true
	case Inject:
		return true
	case None:
		return true
	case Shadow:
		return true
	case Skip:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// ExplainRequest defines model for ExplainRequest.
type ExplainRequest struct {
	Prompt       string  `json:"prompt"`
	SessionModel *string `json:"session_model,omitempty"`
	SubagentType *string `json:"subagent_type,omitempty"`
}

// Explanation Classification, the routing decision, and the per-stage trace.
type Explanation struct {
	Advice               *string                      `json:"advice,omitempty"`
	Chars                *int                         `json:"chars,omitempty"`
	Class                *string                      `json:"class,omitempty"`
	Confidence           *int                         `json:"confidence,omitempty"`
	Danger               *bool                        `json:"danger,omitempty"`
	Lang                 *string                      `json:"lang,omitempty"`
	Margin               *int                         `json:"margin,omitempty"`
	SubagentDecision     Explanation_SubagentDecision `json:"subagent_decision"`
	Trace                Explanation_Trace            `json:"trace"`
	AdditionalProperties map[string]interface{}       `json:"-"`
}

// ExplanationSubagentDecisionAction defines model for Explanation.SubagentDecision.Action.
type ExplanationSubagentDecisionAction string

// Explanation_SubagentDecision defines model for Explanation.SubagentDecision.
type Explanation_SubagentDecision struct {
	Action               ExplanationSubagentDecisionAction `json:"action"`
	Reason               string                            `json:"reason"`
	Target               *string                           `json:"target,omitempty"`
	AdditionalProperties map[string]interface{}            `json:"-"`
}

// Explanation_Trace defines model for Explanation.Trace.
type Explanation_Trace struct {
	Path                 *[]string              `json:"path,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LedgerEvent defines model for LedgerEvent.
type LedgerEvent struct {
	Action               *string                `json:"action,omitempty"`
	At                   time.Time              `json:"at"`
	Class                *string                `json:"class,omitempty"`
	Event                string                 `json:"event"`
	Reason               *string                `json:"reason,omitempty"`
	Target               *string                `json:"target,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Report Ledger summary; every rate comes with its denominator.
type Report struct {
	Entries              int                    `json:"entries"`
	Errors               int                    `json:"errors"`
	Prompts              map[string]interface{} `json:"prompts"`
	Results              map[string]interface{} `json:"results"`
	Subagents            map[string]interface{} `json:"subagents"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	SinceSeconds *int `form:"since_seconds,omitempty" json:"since_seconds,omitempty"`
}

// GetReportParams defines parameters for GetReport.
type GetReportParams struct {
	Days *float64 `form:"days,omitempty" json:"days,omitempty"`
}

// PostExplainJSONRequestBody defines body for PostExplain for application/json ContentType.
type PostExplainJSONRequestBody = ExplainRequest

// Getter for additional properties for Explanation. Returns the specified
// element and whether it was found
func (a Explanation) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Explanation
func (a *Explanation) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Explanation to handle AdditionalProperties
func (a *Explanation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["advice"]; found {
		err = json.Unmarshal(raw, &a.Advice)
		if err != nil {
			return fmt.Errorf("error reading 'advice': %w", err)
		}
		delete(object, "advice")
	}

	if raw, found := object["chars"]; found {
		err = json.Unmarshal(raw, &a.Chars)
		if err != nil {
			return fmt.Errorf("error reading 'chars': %w", err)
		}
		delete(object, "chars")
	}

	if raw, found := object["class"]; found {
		err = json.Unmarshal(raw, &a.Class)
		if err != nil {
			return fmt.Errorf("error reading 'class': %w", err)
		}
		delete(object, "class")
	}

	if raw, found := object["confidence"]; found {
		err = json.Unmarshal(raw, &a.Confidence)
		if err != nil {
			return fmt.Errorf("error reading 'confidence': %w", err)
		}
		delete(object, "confidence")
	}

	if raw, found := object["danger"]; found {
		err = json.Unmarshal(raw, &a.Danger)
		if err != nil {
			return fmt.Errorf("error reading 'danger': %w", err)
		}
		delete(object, "danger")
	}

	if raw, found := object["lang"]; found {
		err = json.Unmarshal(raw, &a.Lang)
		if err != nil {
			return fmt.Errorf("error reading 'lang': %w", err)
		}
		delete(object, "lang")
	}

	if raw, found := object["margin"]; found {
		err = json.Unmarshal(raw, &a.Margin)
		if err != nil {
			return fmt.Errorf("error reading 'margin': %w", err)
		}
		delete(object, "margin")
	}

	if raw, found := object["subagent_decision"]; found {
		err = json.Unmarshal(raw, &a.SubagentDecision)
		if err != nil {
			return fmt.Errorf("error reading 'subagent_decision': %w", err)
		}
		delete(object, "subagent_decision")
	}

	if raw, found := object["trace"]; found {
		err = json.Unmarshal(raw, &a.Trace)
		if err != nil {
			return fmt.Errorf("error reading 'trace': %w", err)
		}
		delete(object, "trace")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Explanation to handle AdditionalProperties
func (a Explanation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Advice != nil {
		object["advice"], err = json.Marshal(a.Advice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'advice': %w", err)
		}
	}

	if a.Chars != nil {
		object["chars"], err = json.Marshal(a.Chars)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'chars': %w", err)
		}
	}

	if a.Class != nil {
		object["class"], err = json.Marshal(a.Class)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'class': %w", err)
		}
	}

	if a.Confidence != nil {
		object["confidence"], err = json.Marshal(a.Confidence)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'confidence': %w", err)
		}
	}

	if a.Danger != nil {
		object["danger"], err = json.Marshal(a.Danger)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'danger': %w", err)
		}
	}

	if a.Lang != nil {
		object["lang"], err = json.Marshal(a.Lang)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lang': %w", err)
		}
	}

	if a.Margin != nil {
		object["margin"], err = json.Marshal(a.Margin)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'margin': %w", err)
		}
	}

	object["subagent_decision"], err = json.Marshal(a.SubagentDecision)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'subagent_decision': %w", err)
	}

	object["trace"], err = json.Marshal(a.Trace)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'trace': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Explanation_SubagentDecision. Returns the specified
// element and whether it was found
func (a Explanation_SubagentDecision) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Explanation_SubagentDecision
func (a *Explanation_SubagentDecision) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Explanation_SubagentDecision to handle AdditionalProperties
func (a *Explanation_SubagentDecision) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if raw, found := object["reason"]; found {
		err = json.Unmarshal(raw, &a.Reason)
		if err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
		delete(object, "reason")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Explanation_SubagentDecision to handle AdditionalProperties
func (a Explanation_SubagentDecision) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["action"], err = json.Marshal(a.Action)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'action': %w", err)
	}

	object["reason"], err = json.Marshal(a.Reason)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'reason': %w", err)
	}

	if a.Target != nil {
		object["target"], err = json.Marshal(a.Target)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'target': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Explanation_Trace. Returns the specified
// element and whether it was found
func (a Explanation_Trace) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Explanation_Trace
func (a *Explanation_Trace) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Explanation_Trace to handle AdditionalProperties
func (a *Explanation_Trace) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Explanation_Trace to handle AdditionalProperties
func (a Explanation_Trace) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LedgerEvent. Returns the specified
// element and whether it was found
func (a LedgerEvent) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LedgerEvent
func (a *LedgerEvent) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LedgerEvent to handle AdditionalProperties
func (a *LedgerEvent) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if raw, found := object["at"]; found {
		err = json.Unmarshal(raw, &a.At)
		if err != nil {
			return fmt.Errorf("error reading 'at': %w", err)
		}
		delete(object, "at")
	}

	if raw, found := object["class"]; found {
		err = json.Unmarshal(raw, &a.Class)
		if err != nil {
			return fmt.Errorf("error reading 'class': %w", err)
		}
		delete(object, "class")
	}

	if raw, found := object["event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'event': %w", err)
		}
		delete(object, "event")
	}

	if raw, found := object["reason"]; found {
		err = json.Unmarshal(raw, &a.Reason)
		if err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
		delete(object, "reason")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LedgerEvent to handle AdditionalProperties
func (a LedgerEvent) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Action != nil {
		object["action"], err = json.Marshal(a.Action)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'action': %w", err)
		}
	}

	object["at"], err = json.Marshal(a.At)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'at': %w", err)
	}

	if a.Class != nil {
		object["class"], err = json.Marshal(a.Class)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'class': %w", err)
		}
	}

	object["event"], err = json.Marshal(a.Event)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event': %w", err)
	}

	if a.Reason != nil {
		object["reason"], err = json.Marshal(a.Reason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason': %w", err)
		}
	}

	if a.Target != nil {
		object["target"], err = json.Marshal(a.Target)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'target': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Report. Returns the specified
// element and whether it was found
func (a Report) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Report
func (a *Report) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Report to handle AdditionalProperties
func (a *Report) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entries"]; found {
		err = json.Unmarshal(raw, &a.Entries)
		if err != nil {
			return fmt.Errorf("error reading 'entries': %w", err)
		}
		delete(object, "entries")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["prompts"]; found {
		err = json.Unmarshal(raw, &a.Prompts)
		if err != nil {
			return fmt.Errorf("error reading 'prompts': %w", err)
		}
		delete(object, "prompts")
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &a.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
		delete(object, "results")
	}

	if raw, found := object["subagents"]; found {
		err = json.Unmarshal(raw, &a.Subagents)
		if err != nil {
			return fmt.Errorf("error reading 'subagents': %w", err)
		}
		delete(object, "subagents")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Report to handle AdditionalProperties
func (a Report) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["entries"], err = json.Marshal(a.Entries)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'entries': %w", err)
	}

	object["errors"], err = json.Marshal(a.Errors)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'errors': %w", err)
	}

	if a.Prompts != nil {
		object["prompts"], err = json.Marshal(a.Prompts)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'prompts': %w", err)
		}
	}

	if a.Results != nil {
		object["results"], err = json.Marshal(a.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}

	if a.Subagents != nil {
		object["subagents"], err = json.Marshal(a.Subagents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subagents': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetEvents Stream new ledger entries as Server-Sent Events
	// (GET /v1/events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// PostExplain Explain how a brief would be classified and routed
	// (POST /v1/explain)
	PostExplain(w http.ResponseWriter, r *http.Request)
	// GetReport Summarise the routing ledger
	// (GET /v1/report)
	GetReport(w http.ResponseWriter, r *http.Request, params GetReportParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "since_seconds" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since_seconds", r.URL.Query(), &params.SinceSeconds, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since_seconds"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since_seconds", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExplain operation middleware
func (siw *ServerInterfaceWrapper) PostExplain(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExplain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReport operation middleware
func (siw *ServerInterfaceWrapper) GetReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReportParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", r.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/report", wrapper.GetReport)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/explain", wrapper.PostExplain)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.GetEvents)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEventsRequestObject struct {
	Params GetEventsParams
}

type GetEventsResponseObject interface {
	VisitGetEventsResponse(w http.ResponseWriter) error
}

type GetEvents200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetEvents200TexteventStreamResponse) VisitGetEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type GetEvents400JSONResponse Error

func (response GetEvents400JSONResponse) VisitGetEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostExplainRequestObject struct {
	Body *PostExplainJSONRequestBody
}

type PostExplainResponseObject interface {
	VisitPostExplainResponse(w http.ResponseWriter) error
}

type PostExplain200JSONResponse Explanation

func (response PostExplain200JSONResponse) VisitPostExplainResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostExplain400JSONResponse Error

func (response PostExplain400JSONResponse) VisitPostExplainResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReportRequestObject struct {
	Params GetReportParams
}

type GetReportResponseObject interface {
	VisitGetReportResponse(w http.ResponseWriter) error
}

type GetReport200JSONResponse Report

func (response GetReport200JSONResponse) VisitGetReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReport400JSONResponse Error

func (response GetReport400JSONResponse) VisitGetReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetEvents Stream new ledger entries as Server-Sent Events
	// (GET /v1/events)
	GetEvents(ctx context.Context, request GetEventsRequestObject) (GetEventsResponseObject, error)
	// PostExplain Explain how a brief would be classified and routed
	// (POST /v1/explain)
	PostExplain(ctx context.Context, request PostExplainRequestObject) (PostExplainResponseObject, error)
	// GetReport Summarise the routing ledger
	// (GET /v1/report)
	GetReport(ctx context.Context, request GetReportRequestObject) (GetReportResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEvents operation middleware
func (sh *strictHandler) GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams) {
	var request GetEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvents(ctx, request.(GetEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventsResponseObject); ok {
		if err := validResponse.VisitGetEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostExplain operation middleware
func (sh *strictHandler) PostExplain(w http.ResponseWriter, r *http.Request) {
	var request PostExplainRequestObject

	var body PostExplainJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostExplain(ctx, request.(PostExplainRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExplain")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostExplainResponseObject); ok {
		if err := validResponse.VisitPostExplainResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReport operation middleware
func (sh *strictHandler) GetReport(w http.ResponseWriter, r *http.Request, params GetReportParams) {
	var request GetReportRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReport(ctx, request.(GetReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReportResponseObject); ok {
		if err := validResponse.VisitGetReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFdtb9w4Dv4rhO6AawHPW5o2B/dT7zbYBuguima/NUHLsThjNbbkkvJMZoP57wvJ9rx6mrZomy/RWBZN",
	"Pg/5kHpQmSsrZ8l6UemDkiynEuPyktlxWFTsKmJvKD4uSQTnFJZ+VZFKlXg2dq7W60Qxfa4Nk1bp+82L",
	"t0n3opt+osyrdaIu76sCjX1Hn2sSH2yh1sYbZ7F4u/O5GRZCyYEHFbuyiodKvH9Ddu5zlZ6Nw1+iSmO7",
	"R5Pk0MNECYkYZz+UTlMRTGiaYV14laqswFrTwFW1DJ4PnqvkwHyftXqKc7L+Q7Oza21OlhiLQVVz5YQe",
	"t3aAXhvkSfAsBrROI+e5pkRpkoxN1byq/l+giJmZLJ5NwOcE7Gpv7Bw0ZUbiU7Q67lTEA/E4J/CMGQ3V",
	"IQ+oFybrS4REZTmy7OwY62lOHLeCE/2HnJ0ZTTaj/pMabVht96bOFYQ27BVo571GS+S5sf0GN/R1wT8G",
	"50H8WUcB2boMpFlnA9PGRqoSJTlqt1SJQrkLP+9MtcPo1kkmFGd7/ffIc/KPV1vrzMZWX+JEHr8txgpD",
	"vj4o46nsZ619gMy4Uuvtg+6zB34eY9751efxa8KicWDfLfHoa9mF3t31Irsg7oj9Mn6txe2JPnfekJ4T",
	"Xy7I+u9NlSMPMZqaOS7DSmn0NPCmJNUTzenaoc6nn5JbXnVf6EPlHVWO/bdJUYMkSF2WyKuXQAviFTB6",
	"gsyVJLA0PgfjBTRZVxqL3vGxBJH13C6Py5tCAzux18irPOb0UaxMUhffca5L+289ecBEF+82gF3TW/c2",
	"wR/zFUwaO3NNu9rl5B2hHjhbrODV2ysQ4gVpmK7gY1Vy8/MjOBt7Q+FcNcXsDgKkPAvtAa480H3odRJe",
	"ubFdZykaqru20j2mbReDmWPQKPnUIWuJrzaOSTRrQ3bc2CUb3xhvbSaQ5aEnCAj5YFQScAxMmOXti5b8",
	"0vHdEF4BN8MGLHMndGNfO/GQE2piMALWecBtXBZLgieTs4vheDgeThIoXIZF7sQn8D5NJ7dPwyG0siQm",
	"fWNjup6fTeAPI9owZZ40tOMNPPntz2tgmhqrQ+TzGlk/Hd5E6TO+IJVGOpHNIM4lg4ARcfPNQMaOLKVq",
	"ElwKOeUqslgZlapnw/HwWUgK9HnMsFEehfPvsG5LPCRaRPtKq1T9Tr7V1pg0lbPSlNHZeBz+Zc76TuWq",
	"qmhHhtGnVkqaMTGs/s00U6n612g7R46aXRm1X4gpt59qf+XUZFTEvq6GMdNbNQjyYBZkSQSynLK7uDla",
	"TEZRg+RLQV0u2kqokLEkTywqff+gTPjq55p4pRIVyFWpEmMz+iCUOavDkW1QmzFuHMc2U4Ye898X5+2A",
	"2fzejnAbXVnfPoqmp3vfxDEQz4TlPpyHQnyE3CsL19eX0Jx9CSHVIZr7j4BGjzEtYadRDUOqnP9AVpt7",
	"QY9re3huaspCC0+UdGOBQ8keEn4d4wFLy04vWqkDFLiOmTK4JuuhJXiTEc1FIk4ITnpy4q0T3942VKOl",
	"JP5/Tq9+HB77d5n1vmYHVV//xBrbvQycKLQdpf11yXBlF1gY3anuId8taJC7JSBM2dAMlq4uNEwJsvae",
	"Qjq2gqiGekM5b8aNUyLQDiRfJQIaVydq/yLZmcpcPS3aS1xT/c9evNjVguF4e9u0dTn9SjX4fuDbGE9Q",
	"3mD069neAn5U4HFlhPaGgKbWG4tNP2iYqrlQqcq9r9LRaNOF04vz5xdqfbv+ZwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
